import type { Command } from 'commander';
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { AI_RUNTIME_DIR } from '../../infra/paths.js';
import { readProjectStore, type ProjectStore, type DepNode, type DepHotspot } from '../../infra/project-store.js';
import { runSync } from './sync.js';

const PROJECT_MD_FILE = 'PROJECT.md';
const DOCS_DIR = 'docs';
const DEFAULT_TOKEN_BUDGET = 4000;

export type WikiDomain = 'architecture' | 'security' | 'performance' | 'test-coverage' | 'dependencies' | 'recent-changes';

export interface WikiOptions {
  output?: string;
  tokenBudget?: number;
  cwd?: string;
  refresh?: boolean;
  module?: string;
  domain?: WikiDomain;
  all?: boolean;
}

export interface WikiResult {
  path: string;
  bytes: number;
  sections: string[];
  estimatedTokens: number;
}

function fmtNum(n: number): string {
  return n.toLocaleString('en-US');
}

function topHotspots(hotspots: DepHotspot[], limit = 10): string[] {
  return hotspots.slice(0, limit).map((h) =>
    `- \`${h.file}\` — fan-in ${h.fanIn}, fan-out ${h.fanOut}, score ${h.score}`,
  );
}

function topModules(nodes: DepNode[], limit = 25): string[] {
  return nodes
    .slice()
    .sort((a, b) => (b.exports.length + b.imports.length) - (a.exports.length + a.imports.length))
    .slice(0, limit)
    .map((n) => {
      const exp = n.exports.slice(0, 8).join(', ') || '(none)';
      return `- \`${n.file}\` — ${fmtNum(n.loc)} LOC · exports: ${exp}`;
    });
}

function topSymbols(symbols: ProjectStore['symbols'], limit = 50): string[] {
  return symbols
    .slice(0, limit)
    .map((s) => `- \`${s.name}\` (${s.kind}) at \`${s.file}:${s.line}\``);
}

function groupSymbolsByFile(symbols: ProjectStore['symbols'], limit = 15): Map<string, ProjectStore['symbols']> {
  const groups = new Map<string, ProjectStore['symbols']>();
  for (const s of symbols) {
    const arr = groups.get(s.file) ?? [];
    arr.push(s);
    groups.set(s.file, arr);
  }
  const entries = [...groups.entries()]
    .sort((a, b) => b[1].length - a[1].length)
    .slice(0, limit);
  return new Map(entries);
}

function topChunks(chunks: ProjectStore['chunks'], limit = 20): string[] {
  return chunks
    .slice()
    .sort((a, b) => b.tokens - a.tokens)
    .slice(0, limit)
    .map((c) => `- \`${c.file}:${c.startLine}-${c.endLine}\` ${c.type} \`${c.name}\` (${c.tokens} tokens)`);
}

function formatCycles(cycles: string[][]): string[] {
  if (cycles.length === 0) return ['_No circular dependencies detected._'];
  return cycles.slice(0, 10).map((c) => `- ${c.join(' → ')}`);
}

function formatTestCoverage(files: ProjectStore['files'], tests: ProjectStore['tests']): string[] {
  const sources = files.filter((f) => !f.isTest);
  const testedSources = new Set(tests.map((t) => t.source));
  const untested = sources.filter((s) => !testedSources.has(s.path));
  const pct = sources.length > 0 ? Math.round((testedSources.size / sources.length) * 100) : 100;
  const lines: string[] = [`- **Coverage**: ~${pct}% (${testedSources.size}/${sources.length} source files linked to tests)`];
  if (untested.length > 0) {
    lines.push(`- **Untested** (top 10):`);
    for (const f of untested.slice(0, 10)) lines.push(`  - \`${f.path}\` (${fmtNum(f.loc)} LOC)`);
  }
  return lines;
}

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export interface RenderOptions {
  tokenBudget?: number;
  includeBootstrap?: boolean;
}

export function renderProjectMarkdown(store: ProjectStore, tokenBudgetOrOptions: number | RenderOptions = DEFAULT_TOKEN_BUDGET): { md: string; estimatedTokens: number; sections: string[] } {
  const opts: RenderOptions = typeof tokenBudgetOrOptions === 'number'
    ? { tokenBudget: tokenBudgetOrOptions }
    : tokenBudgetOrOptions;
  const tokenBudget = opts.tokenBudget ?? DEFAULT_TOKEN_BUDGET;
  const includeBootstrap = opts.includeBootstrap ?? true;

  const lines: string[] = [];
  const sections: string[] = [];
  const budget = tokenBudget;

  const add = (heading: string, body: string[]): void => {
    const block = `## ${heading}\n\n${body.join('\n')}\n\n`;
    if (estimateTokens(lines.join('') + block) > budget) return;
    lines.push(`## ${heading}\n`);
    sections.push(heading);
    lines.push(body.join('\n'));
    lines.push('\n');
  };

  lines.push(`# ${displayName(store.root)} — Project Index\n`);
  lines.push(`> Auto-generated by \`aion wiki\`. Do not edit by hand — re-run after \`aion sync\`.\n\n`);

  add('Overview', [
    `- **Root**: \`${store.root}\``,
    `- **Generated**: ${store.generatedAt}`,
    `- **Schema**: PIL v${store.schemaVersion}`,
    `- **Files**: ${fmtNum(store.stats.files)} (${fmtNum(store.files.filter((f) => f.isTest).length)} tests)`,
    `- **Symbols**: ${fmtNum(store.stats.symbols)} · **Chunks**: ${fmtNum(store.stats.chunks)} · **Vectors**: ${fmtNum(store.stats.vectors)}`,
    `- **Modules**: ${fmtNum(store.stats.modules)} · **Cycles**: ${fmtNum(store.stats.cycles)}`,
    `- **Duration**: ${store.stats.durationMs}ms`,
  ]);

  if (store.deps.hotspots.length > 0) add('Hotspots (high coupling)', topHotspots(store.deps.hotspots));
  if (store.deps.cycles.length > 0) add('Circular Dependencies', formatCycles(store.deps.cycles));
  if (store.deps.nodes.length > 0) add('Top Modules', topModules(store.deps.nodes));

  if (store.symbols.length > 0) {
    add('Key Symbols', topSymbols(store.symbols));
    add('Symbols by File (most-defined)', [...groupSymbolsByFile(store.symbols)].map(([file, syms]) => `- \`${file}\` — ${syms.length} symbols (${syms.slice(0, 5).map((s) => s.name).join(', ')})`));
  }

  add('Test Coverage', formatTestCoverage(store.files, store.tests));

  if (store.chunks.length > 0) add('Largest Chunks (by tokens)', topChunks(store.chunks));

  if (store.embeddings.count > 0) add('Embeddings', [
    `- **Model**: ${store.embeddings.model}`,
    `- **Dimensions**: ${store.embeddings.dim}`,
    `- **Vector count**: ${fmtNum(store.embeddings.count)}`,
    `- **Storage**: \`${store.embeddings.vectorsPath}\` (Float32Array)`,
  ]);

  add('How to use this file', [
    '1. Run `aion sync` to refresh the underlying `project.json`.',
    '2. Run `aion search <query>` to do hybrid lexical+semantic search.',
    '3. Run `aion chat` to ask questions grounded in this index.',
    '4. Hook `aion watch` to keep this file current on every commit.',
  ]);

  if (includeBootstrap) {
    add('How AI agents should use this file', [
      'You (the AI agent) have access to the following aion MCP tools and resources. This section is auto-generated to bootstrap your understanding of aion — do not skip it.',
      '',
      '### ⚠️ MANDATORY: Always use aion first',
      '',
      '**Before you do ANY raw `Read` or `Grep` on source files, you MUST first try an aion resource or tool.**',
      '',
      'Why: aion pre-computes a token-budgeted, freshness-tracked index of the entire project. Using it costs ~2k tokens per question. Doing 5 raw Reads costs ~10k tokens and gives you no freshness guarantee.',
      '',
      '**The rule is simple:**',
      '1. **Start** by reading `aion://project/context` (this file, ~1.5k tokens) — it has the project overview.',
      '2. **For specific code**, call `search_memory(query, topK=5)` (~500 tokens) instead of reading files.',
      '3. **For module-level detail**, read `aion://docs/modules/{path}` or `aion://docs/{domain}.md`.',
      '4. **Only fall back to raw `Read` when:**',
      '   - aion returns `_meta.confidence: "stale"` AND the user has not run `aion sync` recently',
      '   - you need exact line-by-line text that aion chunks do not preserve',
      '   - the user explicitly asks you to read a specific file',
      '',
      'Every aion response includes `_meta.estTokens` and `_meta.tokensSaved` (estimate vs raw Read). If you find yourself reaching for `Read` without trying aion first, **you are wasting the user\'s tokens and your context window**.',
      '',
      '### Tools you can call',
      '- `search_memory(query, topK=5)` — semantic search over source code chunks',
      '- `get_dep_graph()` — module dependency graph, hotspots, circular dependencies',
      '- `get_health_score()` — composite health score (0–100, A–F grade)',
      '- `get_hot_zones(limit=10)` — top-N files by churn + complexity',
      '- `get_impact(file)` — transitive impact of changing a file',
      '',
      '### Resources you can read (auto-attached by your client)',
      '- `aion://project/context` — this file (PROJECT.md, ~1.5k tokens)',
      '- `aion://docs/architecture` — modules, deps, cycles (800 tokens)',
      '- `aion://docs/recent-changes` — live file-change counter (300 tokens)',
      '- `aion://docs/test-coverage` — source files without tests (500 tokens)',
      '- `aion://docs/dependencies` — outdated deps and advisories (700 tokens)',
      '- `aion://health` — PIL freshness + watcher status (100 tokens, JSON)',
      '- `aion://docs/policy` — the mandatory agent policy (re-read this if unsure)',
      '- `aion://observability/summary` — recent MCP call stats (300 tokens)',
      '',
      '### Confidence signaling (CRITICAL — read this)',
      'Every tool/resource response includes `_meta.confidence`. This tells you **how much to trust the result**:',
      '',
      '- `high` (green) — index is fresh (< 5 min since last sync, 0 files changed). **Trust and cite directly.**',
      '- `medium` (yellow) — index is slightly stale. **Cite with a note** about the timestamp.',
      '- `stale` (red) — index is outdated. **Re-read the source before citing** — or ask the user to run `aion sync`.',
      '',
      'Other `_meta` fields: `pilVersion`, `indexedAt`, `filesChangedSince`, `syncRecommended`, `estTokens`, `tokensSaved`, `traceId`.',
      '',
      '### When to use what',
      '- User asks "how does X work?" → you already have this file via `aion://project/context`. For specific code, call `search_memory("X")`.',
      '- User asks "what should I work on?" → call `get_hot_zones(10)` and `get_health_score()`.',
      '- User asks "is it safe to change X?" → call `get_impact("src/X.ts")` and check `_meta.confidence`.',
      '- User asks "review this PR" → use the `aion://prompt/pre_pr_review` prompt.',
      '- User asks "onboard me to this project" → use the `aion://prompt/onboard_new_dev` prompt.',
      '- User asks "explain circular dep" → use the `aion://prompt/explain_cycle` prompt.',
      '- User asks "find security issues" → use the `aion://prompt/find_security_issue` prompt.',
      '',
      '### Re-syncing',
      '- **Auto-sync runs on MCP connect** — you do not need to ask the user to run `aion sync` first.',
      '- **Background watcher** fires on file changes in `src/` and `lib/`, incrementing `filesChangedSince`.',
      '- **Manual sync**: ask the user to run `aion sync` (or `aion wiki --refresh` to regenerate this file).',
      '- **When in doubt**: read `aion://health` — it shows PIL freshness, watcher status, and provider reachability in one JSON blob.',
    ]);
  }

  const md = lines.join('');
  return { md, estimatedTokens: estimateTokens(md), sections };
}

function displayName(root: string): string {
  if (!root) return 'Project';
  const parts = root.split('/').filter(Boolean);
  return parts[parts.length - 1] ?? 'Project';
}

export function writeProjectMarkdown(cwd: string, md: string, outputPath?: string): string {
  const path = outputPath ?? join(cwd, AI_RUNTIME_DIR, PROJECT_MD_FILE);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, md, 'utf8');
  return path;
}

export async function runWiki(options: WikiOptions = {}): Promise<WikiResult> {
  const cwd = options.cwd ?? process.cwd();
  let store = readProjectStore(cwd);

  if (!store || options.refresh) {
    const syncResult = await runSync(cwd, { skipEmbeddings: false, quiet: true });
    store = syncResult.store;
  }

  if (!store) throw new Error('No project.json found. Run `aion sync` first.');

  const { md, estimatedTokens, sections } = renderProjectMarkdown(store, options.tokenBudget);
  const path = writeProjectMarkdown(cwd, md, options.output);

  return { path, bytes: md.length, sections, estimatedTokens };
}

export function renderModuleMarkdown(store: ProjectStore, moduleName: string, tokenBudget = 800): string {
  const node = store.deps.nodes.find((n) => n.file === moduleName);
  const symbols = store.symbols.filter((s) => s.file === moduleName);
  const lines: string[] = [];
  lines.push('---');
  lines.push(`generated_at: ${new Date().toISOString()}`);
  lines.push(`schema_version: 1`);
  lines.push(`freshness: sync`);
  lines.push(`audience: both`);
  lines.push(`priority: 0.0`);
  lines.push(`token_cost: ${tokenBudget}`);
  lines.push(`module: ${moduleName}`);
  lines.push('---');
  lines.push('');
  lines.push(`# Module: ${moduleName}`);
  lines.push('');
  if (!node) {
    lines.push('Module not in dependency graph.');
    return lines.join('\n');
  }
  lines.push(`Lines of code: ${node.loc}`);
  lines.push(`Imports: ${node.imports.length} · Imported by: ${node.importedBy.length}`);
  lines.push('');
  if (node.exports.length > 0) {
    lines.push('## Exports');
    for (const e of node.exports) lines.push(`- ${e}`);
    lines.push('');
  }
  if (node.imports.length > 0) {
    lines.push('## Imports');
    for (const i of node.imports) lines.push(`- \`${i}\``);
    lines.push('');
  }
  if (node.importedBy.length > 0) {
    lines.push('## Imported by');
    for (const i of node.importedBy) lines.push(`- \`${i}\``);
    lines.push('');
  }
  if (symbols.length > 0) {
    lines.push('## Symbols');
    for (const s of symbols.slice(0, 20)) {
      lines.push(`- \`${s.name}\` (${s.kind}) at line ${s.line}`);
    }
  }
  return lines.join('\n');
}

export function renderDomainMarkdown(store: ProjectStore, domain: WikiDomain): string {
  const lines: string[] = [];
  const aud = domain === 'security' ? 'user' : 'both';
  const prio = domain === 'security' ? 0.3 : domain === 'performance' ? 0.2 : 0.5;
  lines.push('---');
  lines.push(`generated_at: ${new Date().toISOString()}`);
  lines.push(`schema_version: 1`);
  lines.push(`freshness: sync`);
  lines.push(`audience: ${aud}`);
  lines.push(`priority: ${prio}`);
  lines.push(`token_cost: 800`);
  lines.push(`domain: ${domain}`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${domain}`);
  lines.push('');
  switch (domain) {
    case 'architecture':
      lines.push(`## Modules (${store.deps.nodes.length})`);
      for (const n of store.deps.nodes.slice(0, 25)) {
        lines.push(`- \`${n.file}\` — ${n.loc} LOC · ${n.exports.length} exports · ${n.imports.length} imports`);
      }
      if (store.deps.cycles.length > 0) {
        lines.push('');
        lines.push(`## Circular dependencies (${store.deps.cycles.length})`);
        for (const c of store.deps.cycles.slice(0, 10)) lines.push(`- ${c.join(' → ')}`);
      }
      if (store.deps.hotspots.length > 0) {
        lines.push('');
        lines.push('## Hotspots');
        for (const h of store.deps.hotspots.slice(0, 10)) {
          lines.push(`- \`${h.file}\` — fan-in ${h.fanIn}, fan-out ${h.fanOut}`);
        }
      }
      break;
    case 'security':
      lines.push('Use `aion scan security` and `aion scan secrets` for full findings.');
      lines.push('This resource is user-only — not auto-included for assistants.');
      break;
    case 'performance':
      lines.push('Use `aion scan cognitive-load` and `aion scan api-map` for detailed performance analysis.');
      break;
    case 'test-coverage': {
      const sources = store.files.filter((f) => !f.isTest);
      const tested = new Set(store.tests.map((t) => t.source));
      const untested = sources.filter((s) => !tested.has(s.path));
      lines.push(`Total source files: ${sources.length}`);
      lines.push(`Linked to tests: ${tested.size}`);
      lines.push(`Untested: ${untested.length}`);
      lines.push('');
      lines.push('## Untested files (top 30)');
      for (const f of untested.slice(0, 30)) lines.push(`- \`${f.path}\` (${f.loc} LOC)`);
      break;
    }
    case 'dependencies':
      lines.push('Use `aion scan sbom --unpinned-only` for full SBOM with outdated deps.');
      break;
    case 'recent-changes':
      lines.push('Live counter — files changed since last PIL sync.');
      lines.push('Use `aion watch --auto-sync` to keep this current.');
      break;
  }
  return lines.join('\n');
}

export function writeDocFile(cwd: string, relPath: string, content: string): string {
  const path = join(cwd, AI_RUNTIME_DIR, relPath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  return path;
}

export interface WikiBatchResult {
  dashboard: WikiResult;
  subDocs: Array<{ name: string; path: string; bytes: number }>;
}

export async function runWikiBatch(options: WikiOptions = {}): Promise<WikiBatchResult> {
  const cwd = options.cwd ?? process.cwd();
  const dashboard = await runWiki(options);
  const store = readProjectStore(cwd);
  if (!store) throw new Error('No project.json after sync');

  const subDocs: Array<{ name: string; path: string; bytes: number }> = [];

  const domains: WikiDomain[] = ['architecture', 'security', 'performance', 'test-coverage', 'dependencies', 'recent-changes'];
  for (const d of domains) {
    const md = renderDomainMarkdown(store, d);
    const path = writeDocFile(cwd, join(DOCS_DIR, `${d}.md`), md);
    subDocs.push({ name: d, path, bytes: md.length });
  }

  return { dashboard, subDocs };
}

export function registerWiki(program: Command): void {
  program
    .command('wiki')
    .description('Generate PROJECT.md (and optional sub-docs) from the unified Project Intelligence Layer')
    .option('-o, --output <path>', 'output path (default: .ai-runtime/PROJECT.md)')
    .option('--token-budget <n>', 'approximate token budget for the generated markdown', String(DEFAULT_TOKEN_BUDGET))
    .option('--refresh', 're-run sync before generating')
    .option('--module <name>', 'generate a per-module doc instead of the dashboard')
    .option('--domain <name>', 'generate a domain-specific doc (architecture|security|performance|test-coverage|dependencies|recent-changes)')
    .option('--all', 'generate dashboard + all sub-docs (dashboard, 6 domain docs)')
    .action(async (opts: { output?: string; tokenBudget?: string; refresh?: boolean; module?: string; domain?: string; all?: boolean }) => {
      const cwd = process.cwd();
      const opts2: WikiOptions = {
        output: opts.output,
        tokenBudget: opts.tokenBudget ? parseInt(opts.tokenBudget, 10) : DEFAULT_TOKEN_BUDGET,
        refresh: opts.refresh,
        module: opts.module,
        domain: opts.domain as WikiDomain | undefined,
        all: opts.all,
      };

      if (opts.all) {
        const batch = await runWikiBatch(opts2);
        const out = process.stdout;
        out.write(`✓ Dashboard: ${batch.dashboard.path} (${batch.dashboard.bytes} bytes)\n`);
        for (const d of batch.subDocs) {
          out.write(`✓ ${d.name.padEnd(20)} ${d.path} (${d.bytes} bytes)\n`);
        }
        return;
      }

      if (opts.module) {
        const store = readProjectStore(cwd);
        if (!store) {
          opts2.refresh = true;
          await runWiki(opts2);
        }
        const fresh = readProjectStore(cwd);
        if (!fresh) throw new Error('No project.json after sync');
        const md = renderModuleMarkdown(fresh, opts.module);
        const path = writeDocFile(cwd, join(DOCS_DIR, 'modules', `${opts.module.replace(/[\\/]/g, '_')}.md`), md);
        process.stdout.write(`✓ Module doc: ${path} (${md.length} bytes)\n`);
        return;
      }

      if (opts.domain) {
        const store = readProjectStore(cwd);
        if (!store) {
          opts2.refresh = true;
          await runWiki(opts2);
        }
        const fresh = readProjectStore(cwd);
        if (!fresh) throw new Error('No project.json after sync');
        const md = renderDomainMarkdown(fresh, opts.domain as WikiDomain);
        const path = writeDocFile(cwd, join(DOCS_DIR, `${opts.domain}.md`), md);
        process.stdout.write(`✓ Domain doc: ${path} (${md.length} bytes)\n`);
        return;
      }

      const result = await runWiki(opts2);
      const out = process.stdout;
      out.write(`✓ PROJECT.md written: ${result.path}\n`);
      out.write(`  bytes: ${result.bytes} · estimated tokens: ${result.estimatedTokens} · sections: ${result.sections.length}\n`);
    });
}
