import type { Command } from 'commander';
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { AI_RUNTIME_DIR } from '../../infra/paths.js';
import { readProjectStore, type ProjectStore, type DepNode, type DepHotspot } from '../../infra/project-store.js';
import { runSync } from './sync.js';

const PROJECT_MD_FILE = 'PROJECT.md';
const DEFAULT_TOKEN_BUDGET = 4000;

export interface WikiOptions {
  output?: string;
  tokenBudget?: number;
  cwd?: string;
  refresh?: boolean;
}

export interface WikiResult {
  path: string;
  bytes: number;
  sections: string[];
  estimatedTokens: number;
}

function fmtNum(n: number): string {
  return n.toLocaleString('en-US');
}

function topHotspots(hotspots: DepHotspot[], limit = 10): string[] {
  return hotspots.slice(0, limit).map((h) =>
    `- \`${h.file}\` — fan-in ${h.fanIn}, fan-out ${h.fanOut}, score ${h.score}`,
  );
}

function topModules(nodes: DepNode[], limit = 25): string[] {
  return nodes
    .slice()
    .sort((a, b) => (b.exports.length + b.imports.length) - (a.exports.length + a.imports.length))
    .slice(0, limit)
    .map((n) => {
      const exp = n.exports.slice(0, 8).join(', ') || '(none)';
      return `- \`${n.file}\` — ${fmtNum(n.loc)} LOC · exports: ${exp}`;
    });
}

function topSymbols(symbols: ProjectStore['symbols'], limit = 50): string[] {
  return symbols
    .slice(0, limit)
    .map((s) => `- \`${s.name}\` (${s.kind}) at \`${s.file}:${s.line}\``);
}

function groupSymbolsByFile(symbols: ProjectStore['symbols'], limit = 15): Map<string, ProjectStore['symbols']> {
  const groups = new Map<string, ProjectStore['symbols']>();
  for (const s of symbols) {
    const arr = groups.get(s.file) ?? [];
    arr.push(s);
    groups.set(s.file, arr);
  }
  const entries = [...groups.entries()]
    .sort((a, b) => b[1].length - a[1].length)
    .slice(0, limit);
  return new Map(entries);
}

function topChunks(chunks: ProjectStore['chunks'], limit = 20): string[] {
  return chunks
    .slice()
    .sort((a, b) => b.tokens - a.tokens)
    .slice(0, limit)
    .map((c) => `- \`${c.file}:${c.startLine}-${c.endLine}\` ${c.type} \`${c.name}\` (${c.tokens} tokens)`);
}

function formatCycles(cycles: string[][]): string[] {
  if (cycles.length === 0) return ['_No circular dependencies detected._'];
  return cycles.slice(0, 10).map((c) => `- ${c.join(' → ')}`);
}

function formatTestCoverage(files: ProjectStore['files'], tests: ProjectStore['tests']): string[] {
  const sources = files.filter((f) => !f.isTest);
  const testedSources = new Set(tests.map((t) => t.source));
  const untested = sources.filter((s) => !testedSources.has(s.path));
  const pct = sources.length > 0 ? Math.round((testedSources.size / sources.length) * 100) : 100;
  const lines: string[] = [`- **Coverage**: ~${pct}% (${testedSources.size}/${sources.length} source files linked to tests)`];
  if (untested.length > 0) {
    lines.push(`- **Untested** (top 10):`);
    for (const f of untested.slice(0, 10)) lines.push(`  - \`${f.path}\` (${fmtNum(f.loc)} LOC)`);
  }
  return lines;
}

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export function renderProjectMarkdown(store: ProjectStore, tokenBudget = DEFAULT_TOKEN_BUDGET): { md: string; estimatedTokens: number; sections: string[] } {
  const lines: string[] = [];
  const sections: string[] = [];
  const budget = tokenBudget;

  const add = (heading: string, body: string[]): void => {
    const block = `## ${heading}\n\n${body.join('\n')}\n\n`;
    if (estimateTokens(lines.join('') + block) > budget) return;
    lines.push(`## ${heading}\n`);
    sections.push(heading);
    lines.push(body.join('\n'));
    lines.push('\n');
  };

  lines.push(`# ${displayName(store.root)} — Project Index\n`);
  lines.push(`> Auto-generated by \`aion wiki\`. Do not edit by hand — re-run after \`aion sync\`.\n\n`);

  add('Overview', [
    `- **Root**: \`${store.root}\``,
    `- **Generated**: ${store.generatedAt}`,
    `- **Schema**: PIL v${store.schemaVersion}`,
    `- **Files**: ${fmtNum(store.stats.files)} (${fmtNum(store.files.filter((f) => f.isTest).length)} tests)`,
    `- **Symbols**: ${fmtNum(store.stats.symbols)} · **Chunks**: ${fmtNum(store.stats.chunks)} · **Vectors**: ${fmtNum(store.stats.vectors)}`,
    `- **Modules**: ${fmtNum(store.stats.modules)} · **Cycles**: ${fmtNum(store.stats.cycles)}`,
    `- **Duration**: ${store.stats.durationMs}ms`,
  ]);

  if (store.deps.hotspots.length > 0) add('Hotspots (high coupling)', topHotspots(store.deps.hotspots));
  if (store.deps.cycles.length > 0) add('Circular Dependencies', formatCycles(store.deps.cycles));
  if (store.deps.nodes.length > 0) add('Top Modules', topModules(store.deps.nodes));

  if (store.symbols.length > 0) {
    add('Key Symbols', topSymbols(store.symbols));
    add('Symbols by File (most-defined)', [...groupSymbolsByFile(store.symbols)].map(([file, syms]) => `- \`${file}\` — ${syms.length} symbols (${syms.slice(0, 5).map((s) => s.name).join(', ')})`));
  }

  add('Test Coverage', formatTestCoverage(store.files, store.tests));

  if (store.chunks.length > 0) add('Largest Chunks (by tokens)', topChunks(store.chunks));

  if (store.embeddings.count > 0) add('Embeddings', [
    `- **Model**: ${store.embeddings.model}`,
    `- **Dimensions**: ${store.embeddings.dim}`,
    `- **Vector count**: ${fmtNum(store.embeddings.count)}`,
    `- **Storage**: \`${store.embeddings.vectorsPath}\` (Float32Array)`,
  ]);

  add('How to use this file', [
    '1. Run `aion sync` to refresh the underlying `project.json`.',
    '2. Run `aion search <query>` to do hybrid lexical+semantic search.',
    '3. Run `aion chat` to ask questions grounded in this index.',
    '4. Hook `aion watch` to keep this file current on every commit.',
  ]);

  const md = lines.join('');
  return { md, estimatedTokens: estimateTokens(md), sections };
}

function displayName(root: string): string {
  if (!root) return 'Project';
  const parts = root.split('/').filter(Boolean);
  return parts[parts.length - 1] ?? 'Project';
}

export function writeProjectMarkdown(cwd: string, md: string, outputPath?: string): string {
  const path = outputPath ?? join(cwd, AI_RUNTIME_DIR, PROJECT_MD_FILE);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, md, 'utf8');
  return path;
}

export async function runWiki(options: WikiOptions = {}): Promise<WikiResult> {
  const cwd = options.cwd ?? process.cwd();
  let store = readProjectStore(cwd);

  if (!store || options.refresh) {
    const syncResult = await runSync(cwd, { skipEmbeddings: false, quiet: true });
    store = syncResult.store;
  }

  if (!store) throw new Error('No project.json found. Run `aion sync` first.');

  const { md, estimatedTokens, sections } = renderProjectMarkdown(store, options.tokenBudget);
  const path = writeProjectMarkdown(cwd, md, options.output);

  return { path, bytes: md.length, sections, estimatedTokens };
}

export function registerWiki(program: Command): void {
  program
    .command('wiki')
    .description('Generate PROJECT.md from the unified Project Intelligence Layer')
    .option('-o, --output <path>', 'output path (default: .ai-runtime/PROJECT.md)')
    .option('--token-budget <n>', 'approximate token budget for the generated markdown', String(DEFAULT_TOKEN_BUDGET))
    .option('--refresh', 're-run sync before generating')
    .action(async (opts: { output?: string; tokenBudget?: string; refresh?: boolean }) => {
      const result = await runWiki({
        output: opts.output,
        tokenBudget: opts.tokenBudget ? parseInt(opts.tokenBudget, 10) : DEFAULT_TOKEN_BUDGET,
        refresh: opts.refresh,
      });
      const out = process.stdout;
      out.write(`✓ PROJECT.md written: ${result.path}\n`);
      out.write(`  bytes: ${result.bytes} · estimated tokens: ${result.estimatedTokens} · sections: ${result.sections.length}\n`);
    });
}
